databases:
  - name: microverseprojectcapstone
    databaseName: microverseprojectcapstone
    user: microverseprojectcapstone_user

services:
  - type: web
    name: mybudgetappproject
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverseprojectcapstone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
