default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: new

development:
  <<: *default
  database: BudgetAppFinal

test:
  <<: *default
  database: BudgetAppFinal

production:
  <<: *default
  database: BudgetAppFinal
